# Generated by Django 3.2.7 on 2021-09-04 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Storeapp', '0002_productfeatures_productfeaturevalidators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturevalidators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturevalidators',
            name='feature',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductFeatureValidators',
        ),
    ]
